# Welcome to Jekyll!
#

# Site settings
title: XVIII DICE
description: |
  Celebremos una vez más el **Día Internacional de la Corrección de Estilo** refleccionando en torno a las semejanzas y diferencias que enfrentamos mujeres y hombres en el ámbito editorial.
owner: PEAC # or company name
first_published: 2024 # if migrating another site, the year of your first publish
email: informacion@peac.mx
baseurl: "/xviii-dice" # the subpath of your site, e.g. /blog
url: "https://peac.mx" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/peacmx
  # github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/profesionales-de-la-edición-ac
  facebook-official: https://facebook.com/profesionales.delaedicion
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/@PEAC_MX
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
